<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <ClassIslandPluginSdkVersion>1.7.106.2-dev-v2</ClassIslandPluginSdkVersion>
  </PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="ClassIsland.PluginSdk" Version="$(ClassIslandPluginSdkVersion)">
			<ExcludeAssets>runtime</ExcludeAssets>
		</PackageReference>
	</ItemGroup>
	
	<ItemGroup Condition="'$(VCTargetsPath)' != ''">
	  <ProjectReference Include="..\uiaccess\uiaccess.vcxproj">
	    <ReferenceOutputAssembly>True</ReferenceOutputAssembly>
	    <CopyLocalSatelliteAssemblies>True</CopyLocalSatelliteAssemblies>
	  </ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="manifest.yml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="README.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="icon.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
